--- #YAML:1.0
name:                BBS-Client
version:             0.01
abstract:            BBS Client
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Encode:                        0
    Lingua::ZH::Wrap:              0
    Net::Telnet:                   0
    Text::Iconv:                   0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Cornelius Lin (cornelius.howl@gmail.com)
